### ISSUE TITLE
Can we keep SEDkit and synth_fit separate?

### ISSUE THREAD

**Issue by stephtdouglas** [BDNYC/synth_fit#18]
i.e. can they not be dependent on each other? Like here: https://github.com/BDNYC/synth_fit/blob/master/synth_fit/utilities.py where synth_fit tries to import SEDkit to get the photometric filters, which shouldn't be necessary for spectrum fitting.

**Comment by ECGonzales** [comment]
Synth fit isn't dependent on SEDkit on my fork. I can do a pull request to master if we want

**Comment by stephtdouglas** [comment]
Perfect, then nvm! I think I'd like Evan to make sure he can run what's here (he just commented out the SEDkit lines) before we do another pull request, but I'll close the issue :) Thanks!

**Comment by ECGonzales** [comment]
I don't think he can run what is there as is. I had to remove a bunch of lines and update things calling SEDkit since you still need utilities.py but just some of it.

**Comment by stephtdouglas** [comment]
Gotcha. I just had him comment out the SEDkit lines and keep utilities.py, since in theory the version he has worked for Paige on the data/model that she sent us so I was going to have him try to run that first. 

How about this - @eeswim, if things don't work fairly quickly today, let us know? Then it might be time to use Eileen's new version

**Comment by ec-morris** [comment]
Things worked out with this version, with the minor edit I made and the commented out portion referencing SEDkit -- but it would be good to be working with the latest version -- @ECGonzales, could you open a pull request updating to what you're working with now?
